spring.application.name=demo
# Database URL (jar tu vegle nav dile asel tar snapgram_db chya jagi te nav tak)
spring.datasource.url=jdbc:postgresql://localhost:5432/snapgram_db

# Tuza Postgres cha Username (default postgres asto)
spring.datasource.username=postgres

# Tu install kartaana jo PASSWORD thevla hota to ithe tak
spring.datasource.password=Avanti2003

# Hibernate chi jaadu (hi line aapo-aap database madhe tables banvte)
spring.jpa.hibernate.ddl-auto=update

# SQL queries terminal madhe bghnyasathi
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect