spring.application.name=demo
# Purna JDBC URL ithe paste kar
spring.datasource.url=jdbc:postgresql://ep-square-mud-ai11na0c-pooler.c-4.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_nBqVy1vCkoc5&sslmode=require&channelBinding=require

# Neon dashboard varun Username aani Password tak
spring.datasource.username=neondb_owner
spring.datasource.password=npg_nBqVy1vCkoc5

# Baki settings same rahtil
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect